<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ur10_calibration</name>
  <version>0.0.1</version>
  <description>Helper package for UR10 ArUco calibration workflow</description>
  <maintainer email="richard@example.com">Richard</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>ur_dashboard_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>python3-pyqt5</depend>
  <depend>builtin_interfaces</depend>
  <depend>std_srvs</depend>
  <depend>trajectory_msgs</depend>
  <depend>control_msgs</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>python3-yaml</depend>
  <depend>moveit_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>python3-opencv</depend>
  <depend>python3-numpy</depend>
  <depend>ament_index_python</depend>
  <exec_depend>ur10_custom_description</exec_depend>
  <exec_depend>ur_moveit_config</exec_depend>
  <exec_depend>ur_robot_driver</exec_depend>
  <exec_depend>realsense2_camera</exec_depend>
  <exec_depend>aruco_ros</exec_depend>
  <exec_depend>easy_handeye2</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
